# Generated by Django 4.2.17 on 2024-12-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_life", "0003_cardconsumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostfound",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="lostfound",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="lostfound",
            name="location",
            field=models.CharField(max_length=100, verbose_name="地点"),
        ),
        migrations.AlterField(
            model_name="lostfound",
            name="status",
            field=models.CharField(
                choices=[("lost", "丢失"), ("claimed", "认领"), ("completed", "已完成")],
                default="lost",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="lostfound",
            name="title",
            field=models.CharField(max_length=100, verbose_name="标题"),
        ),
        migrations.AlterModelTable(
            name="lostfound",
            table=None,
        ),
    ]
