# Generated by Django 4.2.17 on 2024-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campus_life",
            "0004_lostfound_updated_at_alter_lostfound_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lostfound",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lost_found/%Y/%m/",
                verbose_name="物品图片",
            ),
        ),
    ]
