# Generated by Django 4.2.17 on 2024-12-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_life", "0005_lostfound_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostfound",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="lost_found", verbose_name="物品图片"
            ),
        ),
    ]
