# Generated by Django 4.2.17 on 2024-12-22 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campus_life", "0007_activity_current_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "活动",
                "verbose_name_plural": "活动",
            },
        ),
        migrations.AlterModelTable(
            name="activity",
            table=None,
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="参加时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campus_life.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "活动参与者",
                "verbose_name_plural": "活动参与者",
                "unique_together": {("activity", "user")},
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_activities",
                through="campus_life.ActivityParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参与者",
            ),
        ),
    ]
