# Generated by Django 4.2.17 on 2024-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "学生"), ("teacher", "教师"), ("admin", "管理员")],
                default="student",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
