# Generated by Django 4.2.17 on 2024-12-18 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名称")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="课程代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="课程描述")),
                ("credit", models.IntegerField(verbose_name="学分")),
                ("capacity", models.IntegerField(verbose_name="课程容量")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "周一"),
                            (2, "周二"),
                            (3, "周三"),
                            (4, "周四"),
                            (5, "周五"),
                            (6, "周六"),
                            (7, "周日"),
                        ],
                        verbose_name="上课星期",
                    ),
                ),
                (
                    "time_slot",
                    models.IntegerField(
                        choices=[
                            (1, "第一节 (8:00-9:40)"),
                            (2, "第二节 (10:00-11:40)"),
                            (3, "第三节 (14:00-15:40)"),
                            (4, "第四节 (16:00-17:40)"),
                            (5, "第五节 (19:00-20:40)"),
                        ],
                        verbose_name="上课时间",
                    ),
                ),
                ("classroom", models.CharField(max_length=50, verbose_name="教室")),
                ("semester", models.CharField(max_length=20, verbose_name="学期")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "周一"),
                            (2, "周二"),
                            (3, "周三"),
                            (4, "周四"),
                            (5, "周五"),
                            (6, "周六"),
                            (7, "周日"),
                        ],
                        verbose_name="星期",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("classroom", models.CharField(max_length=50, verbose_name="教室")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academic.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程安排",
                "verbose_name_plural": "课程安排",
                "db_table": "course_schedules",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True, verbose_name="成绩")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="选课时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academic.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "选课记录",
                "verbose_name_plural": "选课记录",
                "db_table": "enrollments",
                "unique_together": {("student", "course")},
            },
        ),
    ]
