# Generated by Django 4.2.17 on 2024-12-18 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0003_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="course",
            name="weekday",
        ),
        migrations.AddField(
            model_name="course",
            name="college",
            field=models.CharField(
                choices=[
                    ("computer", "计算机科学与技术学院"),
                    ("communication", "通信与信息工程学院"),
                    ("automation", "自动化学院"),
                    ("economics", "经济管理学院"),
                    ("science", "理学院"),
                    ("foreign", "外国语学院"),
                ],
                default="computer",
                max_length=50,
                verbose_name="开设学院",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrolled",
            field=models.IntegerField(default=0, verbose_name="已选人数"),
        ),
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.IntegerField(verbose_name="容量"),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, verbose_name="课程代码"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="course",
            table=None,
        ),
    ]
