# Generated by Django 4.2.17 on 2024-12-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_remove_course_classroom_remove_course_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="classroom",
            field=models.CharField(default="待定", max_length=50, verbose_name="教室"),
        ),
        migrations.AddField(
            model_name="course",
            name="time_slot",
            field=models.IntegerField(
                choices=[
                    (1, "第一节 (8:00-9:40)"),
                    (2, "第二节 (10:00-11:40)"),
                    (3, "第三节 (14:00-15:40)"),
                    (4, "第四节 (16:00-17:40)"),
                    (5, "第五节 (19:00-20:40)"),
                ],
                default=1,
                verbose_name="上课时间段",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "周一"),
                    (2, "周二"),
                    (3, "周三"),
                    (4, "周四"),
                    (5, "周五"),
                    (6, "周六"),
                    (7, "周日"),
                ],
                default=1,
                verbose_name="上课星期",
            ),
        ),
    ]
