# Generated by Django 4.2.17 on 2024-12-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_course_classroom_course_time_slot_course_weekday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="course",
            name="time_slot",
        ),
        migrations.AlterField(
            model_name="course",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "周一"),
                    (2, "周二"),
                    (3, "周三"),
                    (4, "周四"),
                    (5, "周五"),
                    (6, "周六"),
                    (7, "周日"),
                ],
                verbose_name="上课日期",
            ),
        ),
    ]
