# Generated by Django 4.2.17 on 2024-12-21 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_remove_course_classroom_remove_course_time_slot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="classroom",
            field=models.CharField(default="待定", max_length=50, verbose_name="教室"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="下课时间"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="上课时间"
            ),
        ),
    ]
