# Generated by Django 4.2.17 on 2024-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_course_classroom_course_end_time_course_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("required", "必修课"), ("elective", "选修课")],
                default="required",
                max_length=20,
                verbose_name="课程类型",
            ),
        ),
    ]
